### ISSUE TITLE
Add Keyboard Controls

### ISSUE THREAD

**Issue by Knochenmark** [JutJut/game-shooter#5]

**Comment by mbos2** [comment]
Don't we have that? 🤓

**Comment by Knochenmark** [comment]
@mbos2 So we can close it? Or rewrite the story to add further controls :)

**Comment by mbos2** [comment]
We can close this.
I think we should not open any other issue regarding adding control, but rather feature what should some controll do and in what cases, so we doon't get confused on naming :P

I have created global config for controls _keboard.ts. You can just add/remove controls there, as the object is loaded in game.ts :`**this.keyboardInputs = this.input.keyboard.addKeys(movementKeys)`**
